version: '3'
services:
  expo:
    build: .
    ports:
      - "19000:19000"  # Puerto de API
      - "19001:19001"  # Puerto de WebSocket
      - "19002:19002"  # Interfaz web
    volumes:
      - .:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
